services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      # DEV_SERVER_URL is the URL of the development server that the backend
      # can communicate with. This is passed as an environment variable from
      # the host machine's environment or .env file. It could be used for
      # development purposes, such as connecting to frontend services or
      # external APIs during development.
      - DEV_SERVER_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - binod-network

networks:
  binod-network:
    driver: bridge 