services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEV_SERVER_URL=http://localhost:3000
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - MODEL=${MODEL}
      - OPENROUTER_ENDPOINT=${OPENROUTER_ENDPOINT}
      - COMPOSE_BAKE=true
      
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - binod-network

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"  # Redis Insight GUI
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS="--requirepass mypassword"
    networks:
      - binod-network



networks:
  binod-network:
    driver: bridge

volumes:
  redis-data: 